---
title: "My Growth as a Data Scientist"
format: html
editor: visual
---

***Describe how you have improved as a practitioner and student of data science this quarter through your work in the course.***

-   Focus specifically on data science concepts and the skills we employed in learning them, not a laundry list of topics that you learned (those are in the syllabus, so I know them already).

-   Focus on a small number of specific areas of growth for you that happened in STAT 331. Identify at least one artifact in your portfolio that illustrates each area of growth and explain how this artifact shows growth in the way you are describing.

The primary area of data science I improved upon as a student through this class is in how I optimize my processes for efficiency. The first aspect I improved in this respect is by reducing the number of single use variables. By reducing the number of single use variables in my code it allows for myself and others to understand the objective of a code chunks easier when reviewing the code as it is not broken up into multiple unnecessary steps. In addition to this it prevents errors made due to accessing the wrong variables, as well as having redundant variable names. Another aspect I have improved in optimizing my code is through using pipelines (dplyr) to streamline multi-step processes into one code chunk. Finally, I think mentally the way I think about a problem before even writing code has improved which reduces the amount of times I have to review code to improve efficiencies. I believe this is most visible in my lab 5 as it accomplishes numerous multi-step processes with multiple data sets without creating a large number of unnecessary intermittent variables through the use of piping data. Also, in my revising of this lab I significantly reduced the number of single use variables and also improved overall efficiency through using piping and changing my order of operations.
