---
title: "The Power of Efficiency"
format: html
editor: visual
---

As we’ve said in the class efficiency is a pivotal component of statistical computing (and data science). In this essay, give an explanation of what that term “efficiency” means in relation to statistical computing and describe some places where you encountered efficiency and understood its importance. Your essay should address the following questions:

-   What is the definition of “efficiency”?

-   What does efficiency look like in statistical computing / data science?

-   What does efficiency allow you to do?

-   Why is efficiency important?

-   Where did you encounter efficiency, and what were some [“a-ha” moments](https://www.merriam-webster.com/dictionary/aha%20moment) you had about efficiency? (For the latter, tie each a-ha moment to an artifact in the portfolio.)

I think of efficiency as the ratio of outputted work to inputted energy such as the case in physics. This definition generally applies to most concepts however due to combination of people and computers in the field of data science it must consider inputs by both of the actors. In the context of data science, efficiency can be thought of as minimizing the time (often times by the coder involved, but also by the computer) and computing power it takes to accomplish a task. Within these primary objectives it involves minimizing redundant processes, maximizing clarity of code (for review purposes), generating accurate and reproducible results, and maximizing speed in which steps are accomplished by the coder. In our course these can be accomplished by using piping of data, vectorized functions, and avoiding unnecessary variables. From the coder side of data science, efficiency allows for easier collaboration between individuals and teams as it reduces the clutter in code structure. It also allows for greater productivity as it reduces time it takes to accomplish a task and reduces the likelihood of errors caused by repetitive steps and/or variables. On the computing aspect of data science efficiency allows for greater speed of processes and also allows for larger data sets to be processed as resource strain per unit of data is reduced through efficiency optimization. Efficiency is important because it it helps speed up the timeline for projects requiring statistical analysis. It also reduces errors due to confusing or over complicated work processes, especially in situations involving collaboration. In addition to this efficiency helps reduce costs for companies using data science to improve their business or SAAS businesses where data science is the entire source of revenue for a company. The most frequent encounter with efficiency in this course I had was in data piping. Combining many intermittent steps into one longer process allowed me to debug easier and not lose my place in the process while writing code. I realize how important this was during lab 5 where I implemented multiple questions of the lab using several piping arguments, allowing me to accomplish tasks without many intermittent steps.
